version: '3.9'

services:
    swoole:
        build:
            context: .
            dockerfile: swoole/Dockerfile
        environment:
            - COMPOSER_ALLOW_SUPERUSER=true
            - XDEBUG_CONFIG=client_host=host.docker.internal start_with_request=trigger
            - XDEBUG_MODE=debug
            - XDEBUG_SESSION=PHPSTORM
            - PHP_IDE_CONFIG=serverName=swoole
        ports:
            -   "9501:9501"
        volumes:
            -   ./swoole:/app
        working_dir: /app
        command: php index.php

    swoole-ws:
        build:
            context: .
            dockerfile: swoole/Dockerfile
        environment:
            - COMPOSER_ALLOW_SUPERUSER=true
            - XDEBUG_CONFIG=client_host=host.docker.internal start_with_request=trigger
            - XDEBUG_MODE=debug
            - XDEBUG_SESSION=PHPSTORM
            - PHP_IDE_CONFIG=serverName=swoole
        ports:
            -   "9511:9511"
        volumes:
            -   ./swoole:/app
        working_dir: /app
        command: php ws.php

    rr:
        build:
            context: .
            dockerfile: roadrunner/Dockerfile
        environment:
            COMPOSER_ALLOW_SUPERUSER: true
        ports:
            -   "9502:9502"
        volumes:
            -   ./roadrunner:/app
        working_dir: /app
        command: ./rr serve

    workerman:
        build:
            context: .
            dockerfile: workerman/Dockerfile
        environment:
            - COMPOSER_ALLOW_SUPERUSER=true
            - XDEBUG_CONFIG=client_host=host.docker.internal start_with_request=trigger
            - XDEBUG_MODE=of
            - XDEBUG_SESSION=PHPSTORM
            - PHP_IDE_CONFIG=serverName=workerman
        ports:
            -   "9503:9503"
        volumes:
            -   ./workerman:/app
        working_dir: /app
        command: php index.php start

    node:
        build:
            context: .
            dockerfile: nodejs/Dockerfile
        ports:
            -   "9504:9504"
        volumes:
            -   ./nodejs:/app
        working_dir: /app
        command: node index.js